"""Pydantic models shared across the platform (the platform's data contracts)."""

from powerbi_agent.models.analysis import (
    AnalysisResult,
    ColumnProfile,
    ColumnRole,
    DatasetProfile,
    Insight,
    LogicalType,
    QualityIssue,
    QualityIssueKind,
    QualityReport,
    Severity,
)
from powerbi_agent.models.datasource import DataSource, DataSourceType
from powerbi_agent.models.dax import (
    CalculatedColumnSpec,
    DaxCheck,
    DaxFinding,
    DaxValidationResult,
    MeasureSpec,
)
from powerbi_agent.models.report import (
    FieldRef,
    FilterSpec,
    PageSpec,
    Position,
    ReportSpec,
    VisualSpec,
    VisualType,
)
from powerbi_agent.models.semantic_model import (
    Cardinality,
    ColumnSpec,
    CrossFilter,
    DataType,
    HierarchySpec,
    ModelInfo,
    RelationshipSpec,
    SemanticModelSpec,
    StorageMode,
    SummarizeBy,
    TableKind,
    TableSpec,
)
from powerbi_agent.models.tasks import (
    Capability,
    Intent,
    Plan,
    PlanStep,
    Risk,
    StepResult,
    Task,
    TaskStatus,
)

__all__ = [
    "AnalysisResult",
    "CalculatedColumnSpec",
    "Capability",
    "Cardinality",
    "ColumnProfile",
    "ColumnRole",
    "ColumnSpec",
    "CrossFilter",
    "DataSource",
    "DataSourceType",
    "DataType",
    "DatasetProfile",
    "DaxCheck",
    "DaxFinding",
    "DaxValidationResult",
    "FieldRef",
    "FilterSpec",
    "HierarchySpec",
    "Insight",
    "Intent",
    "LogicalType",
    "MeasureSpec",
    "ModelInfo",
    "PageSpec",
    "Plan",
    "PlanStep",
    "Position",
    "QualityIssue",
    "QualityIssueKind",
    "QualityReport",
    "RelationshipSpec",
    "ReportSpec",
    "Risk",
    "SemanticModelSpec",
    "Severity",
    "StepResult",
    "StorageMode",
    "SummarizeBy",
    "TableKind",
    "TableSpec",
    "Task",
    "TaskStatus",
    "VisualSpec",
    "VisualType",
]
